// Parses the markdown memo string emitted by the backend synthesizer.

export interface MemoField {
  label: string;
  value: string;
  isList: boolean;
  items: string[];
  flagged: boolean; // has ⚠️ critic flag
}

export interface MemoSection {
  title: string;
  fields: MemoField[];
}

export interface MemoCitation {
  idx: number;
  source: string;
  label: string;
  value: string;
  url: string | null;
}

export interface ParsedMemo {
  title: string;
  generatedAt: string;
  sections: MemoSection[];
  citations: MemoCitation[];
}

function finalizeField(
  label: string,
  rawLabelLine: string,
  valueLines: string[],
): MemoField {
  const flagged = rawLabelLine.includes("⚠️") || rawLabelLine.includes("_critic:");
  const nonEmpty = valueLines.filter((l) => l.trim() !== "");
  const isList =
    nonEmpty.length > 0 && nonEmpty.every((l) => l.trim().startsWith("- "));

  if (isList) {
    const items = nonEmpty.map((l) => l.trim().replace(/^- /, ""));
    return { label, value: "", isList: true, items, flagged };
  }
  return {
    label,
    value: nonEmpty.join(" ").trim(),
    isList: false,
    items: [],
    flagged,
  };
}

function parseSectionFields(content: string): MemoField[] {
  const fields: MemoField[] = [];
  const lines = content.split("\n");

  let currentLabel = "";
  let currentRawLine = "";
  let valueLines: string[] = [];
  let inField = false;

  for (const line of lines) {
    // Regular field: **Label** at start of line (agent sections)
    const fieldMatch = line.match(/^\*\*(.+?)\*\*/);
    // Inline bullet field: - **Label:** value  (Executive Summary format)
    const bulletMatch = line.match(/^- \*\*(.+?):\*\*\s*(.+)/);
    // Critic summary line: _Critic review: ..._
    const criticMatch = line.match(/^_Critic review: (.+?)_$/);

    if (fieldMatch) {
      if (inField) {
        fields.push(finalizeField(currentLabel, currentRawLine, valueLines));
      }
      currentLabel = fieldMatch[1].trim();
      currentRawLine = line;
      valueLines = [];
      inField = true;
    } else if (bulletMatch) {
      if (inField) {
        fields.push(finalizeField(currentLabel, currentRawLine, valueLines));
        inField = false;
      }
      fields.push({
        label: bulletMatch[1].trim(),
        value: bulletMatch[2].trim(),
        isList: false,
        items: [],
        flagged: false,
      });
    } else if (criticMatch) {
      if (inField) {
        fields.push(finalizeField(currentLabel, currentRawLine, valueLines));
        inField = false;
      }
      fields.push({
        label: "Critic Review",
        value: criticMatch[1].trim(),
        isList: false,
        items: [],
        flagged: true,
      });
    } else if (inField) {
      valueLines.push(line);
    }
  }

  if (inField) {
    fields.push(finalizeField(currentLabel, currentRawLine, valueLines));
  }

  return fields;
}

function parseCitations(content: string): MemoCitation[] {
  const citations: MemoCitation[] = [];

  for (const line of content.split("\n")) {
    // e.g. "1. **[yfinance]** Revenue: ₹2.3L Cr — [link](https://...)"
    const m = line.match(/^(\d+)\. \*\*\[([^\]]+)\]\*\* (.+)$/);
    if (!m) continue;

    const idx = parseInt(m[1], 10);
    const source = m[2];
    let rest = m[3];

    // Extract trailing URL: " — [text](url)"
    let url: string | null = null;
    const urlMatch = rest.match(/^(.*?) — \[.+?\]\((.+?)\)$/);
    if (urlMatch) {
      rest = urlMatch[1];
      url = urlMatch[2];
    }

    // Split "Label: Value"
    const colonIdx = rest.indexOf(": ");
    const label = colonIdx >= 0 ? rest.slice(0, colonIdx) : rest;
    const value = colonIdx >= 0 ? rest.slice(colonIdx + 2) : "";

    citations.push({ idx, source, label, value, url });
  }

  return citations;
}

export function parseMemo(markdown: string): ParsedMemo {
  // Split on lines that start with "## "
  const chunks = markdown.split(/^(?=## )/m);

  const headerChunk = chunks[0] ?? "";
  const titleMatch = headerChunk.match(/^# (.+)$/m);
  const title = titleMatch?.[1] ?? "";
  const genMatch = headerChunk.match(/_Generated by Meridian · (.+?)_/);
  const generatedAt = genMatch?.[1] ?? "";

  const sections: MemoSection[] = [];
  const citations: MemoCitation[] = [];

  for (const chunk of chunks.slice(1)) {
    const newlineIdx = chunk.indexOf("\n");
    if (newlineIdx === -1) continue;

    const heading = chunk.slice(3, newlineIdx).trim(); // strip "## "
    const rawContent = chunk.slice(newlineIdx + 1);
    // Strip trailing "---" dividers the synthesizer appends between sections
    const content = rawContent.replace(/\n---\n\n?$/, "").trim();

    if (heading === "Citations") {
      citations.push(...parseCitations(content));
    } else {
      sections.push({ title: heading, fields: parseSectionFields(content) });
    }
  }

  return { title, generatedAt, sections, citations };
}
